# Generated by Django 3.1.7 on 2021-05-01 12:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0001_initial'),
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preferences',
            new_name='Preference',
        ),
        migrations.AlterModelOptions(
            name='preference',
            options={'verbose_name': 'Preference', 'verbose_name_plural': 'Prefereces'},
        ),
    ]
